name: TAB
version: 3.0.1
author: NEZNAMY
main: me.neznamy.tab.platforms.bukkit.Main
api-version: 1.13
softdepend: [PlaceholderAPI, Vault, UltraPermissions, LuckPerms, Essentials, LibsDisguises, ProtocolSupport, ViaVersion]
website: "https://github.com/NEZNAMY/TAB"
description: An all-in-one solution that works
commands:
  tab:
